### ISSUE TITLE
Phantomjs timeouts

### ISSUE THREAD

**Issue by hallvors** [Asynchq/boar#5]
If I run the test_ebay.py script in the jannah repo, requesting a webkit tab (and fixing the script to open ebay.de instead of google.de ;)), it tends to end up with some sort of timeout that makes the hub kill the tab before the script is completed. It usually happens during the getScreenshot call.

```
stdout: Starting Tab on port: 55550

info: 55550
Tab: 55550 is alive.
http://127.0.0.1:55550/ping
stdout: ReferenceError: Can't find variable: iam_data


stdout:   https://secureir.ebaystatic.com/rs/c/iam405.js:436 in global code

Tab: 55550 is alive.
http://127.0.0.1:55550/ping
Tab: 55550 is alive.
http://127.0.0.1:55550/ping
Tab: 55550 is alive.
http://127.0.0.1:55550/ping
Tab: 55550 is alive.
http://127.0.0.1:55550/ping
Tab: 55550 is alive.
http://127.0.0.1:55550/ping
killing tab on port 55550
info: Purging :55550
killing tab on port 55550
```
And here's the Python script's output (slightly edited):
```
executing http://127.0.0.1:7331/new 200
{"url":"http://127.0.0.1:55550"}
executing http://127.0.0.1:55550/addCookie 200
{"success":true}
executing http://127.0.0.1:55550/setUserAgent 200
{"success":true}
executing http://127.0.0.1:55550/open 200
{"success":true,"elapsedTime":7085}
executing http://127.0.0.1:55550/waitForResources 200

executing http://127.0.0.1:55550/getResources 200
{"success":true,"resources":{}}

The Resources

executing http://127.0.0.1:55550/setScreenSize 200
{"size":{"height":400,"width":1280}}
executing http://127.0.0.1:55550/getScreenshot
Traceback (most recent call last):
  File "test_ebay.py", line 73, in <module>
    response = do_command(url, "getScreenshot")
  File "test_ebay.py", line 11, in do_command
    data=json.dumps(data), headers=headers)
  File "C:\Python27\lib\site-packages\requests\api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=55550): Max retries exceeded with url: /getScreenshot (Caused by <class 'socket.error'>: [Errno 10054] En eksisterende tilkobling ble tvangslukket av den eksterne verten)
```

I hope we can get to the bottom of this issue and find a workaround or fix.

**Comment by hallvors** [comment]
@seiflotfy , @ronoc  - can you reproduce this problem, or is it just me?

**Comment by seiflotfy** [comment]
Seems like its just you




executing http://localhost:7331/addCookie 200
{"success":true}
executing http://localhost:7331/setUserAgent 200
{"success":true}
executing http://localhost:7331/evaluateOnGecko 200
{"script":"self._page.onLoadFinished = function(){ console.log(\"HELP\"); };"}
executing http://localhost:7331/open 200
{"success":true,"elapsedTime":2508}
executing http://localhost:7331/waitForResources 200

executing http://localhost:7331/getResources 200
{"success":true,"resources":{}}

The Resources 

```
executing http://localhost:7331/setScreenSize 200
{"size":{"height":400,"width":1280}}
executing http://localhost:7331/getScreenshot 200
{"success":true,"data":"..."}
executing http://localhost:7331/evaluate 200
{"script":"function(){return document.getElementsByClassName('ctr-p').length>0}","result":false}
executing http://localhost:7331/getCookies 200
{"cookies":[{"domain":".ebayrtm.com","expires":"Wed, 26 Jul 2017 21:14:00 GMT","expiry":1501103640,"httponly":false,"name":"RUP","path":"/rtm","secure":false,"value":"D1AQAAAU69W%2FmAAAb3R%2Fey%2F%2BZWSAIiAENrYhc1CCcEGQCt4JC2B8DRLIbrpa3uAo4*"},{"domain":".de.ebayrtm.com","expires":"Wed, 26 Jul 2017 21:14:00 GMT","expiry":1501103640,"httponly":false,"name":"RUA","path":"/rtm","secure":false,"value":"D1AQAAAU69W%2FmAAAaK76Dg8HSYG9Vd8h9WkjNNyG%2B9Hzqtr8IE%2FIzaqlKAlJGHXiB7gyIsDlqrxT6CVbR3K7CO%2FG5jrnXRR9FtQh1G%2BFH01qDiARxKCDCw7phFuasCFmjiof3sB5jzA%2Bruf4n7jvBE"},{"domain":".de.ebayrtm.com","expires":"Tue, 26 Jul 2016 21:14:00 GMT","expiry":1469567640,"httponly":false,"name":"TC01","path":"/rtm","secure":false,"value":"gAQDedFtTBAAABQCh1+PAAAAAAAUAhjFQ"},{"domain":".de.ebayrtm.com","expires":"Tue, 26 Jul 2016 21:14:00 GMT","expiry":1469567640,"httponly":false,"name":"M01","path":"/rtm","secure":false,"value":"AgAE"},{"domain":".de.ebayrtm.com","expires":"Tue, 26 Jul 2016 21:14:00 GMT","expiry":1469567640,"httponly":false,"name":"A01","path":"/rtm","secure":false,"value":"QAEAJEW7/AAAAAAAQxxC"},{"domain":".ebay.de","expires":"Wed, 26 Jul 2017 21:14:00 GMT","expiry":1501103640,"httponly":false,"name":"dp1","path":"/","secure":false,"value":"bu1p/QEBfX0BAX19AQA**5797d28c^bl/DE5979060c^pbf/#201000000000000001000200000059790618^cq/0^idm/155b7f08f^"},{"domain":".ebay.de","expires":"Wed, 26 Jul 2017 21:14:00 GMT","expiry":1501103640,"httponly":false,"name":"ebay","path":"/","secure":false,"value":"%5Esbf%3D%23400000000000000100000%5E"},{"domain":".ebay.de","expires":"Tue, 26 Jul 2016 21:13:49 GMT","expiry":1469567629,"httponly":false,"name":"npii","path":"/","secure":false,"value":"bcguid/d15d4c7814e0a623c17143d1fb8104c25797d28d^tguid/d15d489f14e0a6248f66b037ffe0f6ba5797d28d^"},{"domain":".de.ebayrtm.com","expires":"Tue, 26 Jul 2016 21:13:49 GMT","expiry":1469567629,"httponly":false,"name":"PS","path":"/rtm","secure":false,"value":"T.0"},{"domain":".ebay.com","expires":"Tue, 26 Jul 2016 21:13:49 GMT","expiry":1469567629,"httponly":false,"name":"npii","path":"/","secure":false,"value":"bcguid/d15d4c7814e0a623c17143d1fb8104c25797d28d^"},{"domain":".ioam.de","expires":"Sun, 08 May 2016 15:37:42 GMT","expiry":1462721862,"httponly":false,"name":"i00","path":"/","secure":false,"value":"00207f09db358a67555b69f0d0001%3B55b69f0d%3B572f5d46"},{"domain":".doubleclick.net","expires":"Mon, 27 Jul 2015 21:28:49 GMT","expiry":1438032529,"httponly":false,"name":"test_cookie","path":"/","secure":false,"value":"CheckForPermission"},{"domain":".ebay.de","expires":"Tue, 26 Jul 2016 21:13:48 GMT","expiry":1469567628,"httponly":false,"name":"nonsession","path":"/","secure":false,"value":"CgADLAAFVtqYUMQDKACBfHKCMZDE1ZDQ4OWYxNGUwYTYyNDhmNjZiMDM3ZmZlMGY2YmHqiXJa"},{"domain":".ebay.de","expires":"Tue, 26 Jul 2016 21:13:48 GMT","expiry":1469567628,"httponly":true,"name":"s","path":"/","secure":false,"value":"CgAD4ACBVt/CMZDE1ZDQ4OWYxNGUwYTYyNDhmNjZiMDM3ZmZlMGY2YmFL+dz7"},{"domain":"www.ebay.de","expires":"Tue, 26 Jul 2016 21:13:48 GMT","expiry":1469567628,"httponly":true,"name":"JSESSIONID","path":"/","secure":false,"value":"4964ED9C668A4C0391A0326DA25B7DE7"}]}
executing http://localhost:7331/getConsoleLog 200
{"consoleLog":[]}
executing http://localhost:7331/destroy 200
{"success":true}
```

**Comment by seiflotfy** [comment]
What version of phantoms are you using?

**Comment by hallvors** [comment]
2.0 - the latest. Maybe that's the problem - release notes say it contains known regressions :-(

**Comment by seiflotfy** [comment]
yeah me too I am using phantomjs: stable 2.0.0

**Comment by ronoc** [comment]
Any updates here ?

**Comment by seiflotfy** [comment]
can't replicate it

**Comment by seiflotfy** [comment]
I think this should be fixed now that we don't resize anymore (resize got it to wait till all new resources loaded, if failed to do that in time it timed out)
